### ISSUE TITLE
Update stylus version to support bootstrap-stylus and others

### ISSUE THREAD

**Issue by liorch88** [walmartlabs/lumbar#125]
Please update the stylus version, as bootstrap-stylus requires it (and probably others will too)
It does not work with the current stylus version, as they changed the way they handle media queries, which now only works with the latest stylus.

Note that I tried updating it myself but its not so simple: it crashes due to stylus-images incompatibility with the new stylus (I also opened an issue about it: https://github.com/kpdecker/stylus-images/issues/3)

**Comment by kpdecker** [comment]
Released in 5.0.0
